### ISSUE TITLE
Error while installing xpup on my Linux Mint

### ISSUE THREAD

**Issue by ParinVachhani** [ericchiang/xpup#1]
I get thw following error on running the "go get" command as specified in your README.
Error:
"go install github.com/ericchiang/xpup: mkdir /usr/bin/go/: file exists"
I also ran "go install" with the url but gives same error.
Could you help?

**Comment by ericchiang** [comment]
This is more than likely a problem with your Go installation. Can you go get any other library?

If it is a problem with your install, you should follow the instructions here: https://golang.org/doc/install to ensure it's setup correctly. It seems like your GOROOT or GOPATH might be wacky.
